### ISSUE TITLE
RbUI are not compatible with Phlex 2.0 

### ISSUE THREAD

**Issue by cirdes** [ruby-ui/ruby_ui#151]
```bash
Could not find compatible versions

Because every version of rbui depends on phlex ~> 1.10
  and phlex-rails >= 2.0.0.beta2 depends on phlex = 2.0.0.beta2,
  every version of rbui is incompatible with phlex-rails >= 2.0.0.beta2.
So, because Gemfile depends on phlex-rails = 2.0.0.beta2
  and Gemfile depends on rbui >= 0,
  version solving has failed.
```

**Comment by cancelei** [comment]
I had the same issue too.

> As a Gem user, I couldn't make the RBUI work for my Rails app, so I decided to use PhlexyUI until all the bugs were solved.

**Comment by AliOsm** [comment]
I was able to use RBUI with Phlex v2 in this Rails app:
https://github.com/AliOsm/phlex-icons-web-app

I cloned RBUI and updated the gemspec to allow Phlex v2, then I created this initializer:
https://github.com/AliOsm/phlex-icons-web-app/blob/main/config/initializers/rbui.rb

**Comment by SethHorsley** [comment]
This has been fixed and in main now.
