### ISSUE TITLE
uninitialized constant ApplicationComponent::RBUI

### ISSUE THREAD

**Issue by cannikin** [ruby-ui/ruby_ui#156]
Super excited to find this project! But having issues getting started...I've got `phlex` 1.10.3 and `phlex_ui` 0.1.9.

I followed the install instructions to the letter but when loading my first view I'm getting `uninitialized constant ApplicationComponent::RBUI`:

![image](https://github.com/user-attachments/assets/8cb8f9de-95d5-411e-b2aa-38cb992f4f47)

If I change that to `include PhlexUI` then I get past that, but I get another error with any component I try to use:

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/8ede39b3-56d5-483c-b01a-000308f1371b">

If I change that `Table` to `Table.new` then I get past *that* error, but nothing actually renders, just a blank screen. :( 

Looks like the project is transitioning from PhlexUI to RBUI so maybe the docs site is out of date? Do I need to be running on `main` maybe, if I want to get this working until a real `rbui` gem is released? I tried installing the `rbui` gem but it was 0.0.0 and just a placeholder module.

Thanks for any help!

**Comment by SethHorsley** [comment]
The issue is with using phlex_ui. we are changing things a bit and are changing the gem's name. Try putting this in your gemfile:
```ruby
gem "rbui", github: "rbui-labs", branch: "main"
```

**Comment by betogrun** [comment]
> The issue is with using phlex_ui. we are changing things a bit and are changing the gem's name. Try putting this in your gemfile:
> 
> ```ruby
> gem "rbui", github: "rbui-labs", branch: "main"
> ```

@SethHorsley I try adding `gem "rbui", github: "rbui-labs", branch: "main"` to my Gemfile, but it requires authentication.
![image](https://github.com/user-attachments/assets/243b1019-d122-44c5-acae-f5de13c47d0e)

**Comment by betogrun** [comment]
I made it work by adding `gem 'ruby_ui', git: 'https://github.com/rbui-labs/ruby_ui', branch: 'main'` in the Gemfile.

**Comment by SethHorsley** [comment]
@jeduardo824 were you able to fix your issue?
