### ISSUE TITLE
RubyUI becoming more a ShadCN

### ISSUE THREAD

**Issue by stephannv** [ruby-ui/ruby_ui#192]
@SethHorsley, I was talking with @cirdes about making RubyUI simpler and distinct. My idea is making RubyUI to work primarily as a component generator that can be used as development dependency than a ui kit that provides components and js package. It will work more like the Shadcn.

I think this approach will make things simpler. Today we need to have a js package and update it, we need to have code that handles if user is using internal components or using generated components, like tailwind config (it checks gem path to get tailwind classes) or stimulus js checking if a controller exists. We need to have gem dependencies like rouge/tailwind-merge. I'm not sure yet, but maybe it can make importmap/esbuild setup easier.

I think RubyUI can be a "eject-only" lib and stand out for it, adding a command like `rails g ruby_ui card` on each page (like ShadCN). I know that some users will dislike this idea, but we should know what we want, and I think the idea is having a collection of re-usable components that users can copy and paste into their apps, accessible and customizable.

**Comment by cirdes** [comment]
It's an important decision, but it seems to point to the right direction. I'm feeling that we're facing the "jack of all trades and master of none" dilemma. We're trying to please everyone, but in the end, we're facing complexity that slows us down. 

I have been using that approach on ShadCn for a while, and I really like it. Importing that concept to Rails component library aligns with the vision that I believe and also with what @dhh seems to [believe](https://open.spotify.com/episode/57lErmeONVvR1j4vaqyqRT?si=nHX5ho_DSy2sXKsBTpu0eQ&context=spotify%3Ashow%3A23ZxPAyiZx2rTJ4NjYycLN&nd=1&dlsi=ec187a26451f4bca)

In the future, we can release a wrapper around ruby-ui to make it possible to be used without ejecting the components if we want to support that as well.

Let's speed things up by reducing complexity!

**Comment by stephannv** [comment]
Closing this since the last efforts were merged.

**Comment by budu** [comment]
Just to be sure, now that the generator is broken, we need to use the manual installation instruction?

**Comment by stephannv** [comment]
> Just to be sure, now that the generator is broken, we need to use the manual installation instruction?

@budu I'm not sure what is your issue but we fixed an issue on generator last week, it is on main but we need to release a new version to make it available. You can use the gem from github while we don't release the new version:
```ruby
gem "ruby_ui", github: "ruby-ui/ruby_ui"
```

**Comment by budu** [comment]
Yes, that was it, the main branch works! Thanks
